apiVersion: v1
kind: Service
metadata:
  name: platform-np-service
spec:
  selector:
    app: platformservice
  ports:
    - name: platformservice
      protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  